### ISSUE TITLE
Meta: Moving forward

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/mime#153]
This is a meta issue to collect the steps needed to move this crate forward. While it is currently "maintained", in that severe bugs will be merged, it's otherwise rotting. I'm hopeful we can revive it, but I'll need _your_ help.

- [ ] Settle on tenets/values
- [ ] Fix up master (so that it's pointing at code that matters, not a failed design)
- [ ] Propose a design based on the tenets
- [ ] Implement an accepted design proposal

## Related to

- #135
- #52

### 0.1: `Mime(TopLevel::Plain, SubLevel::Text, [])`

This allowed "expressive" matching like `Mime(TopLevel::Text, SubLevel::Plain, _)`.

Cons:
- Needs several imports to construct and to match.
- The `SubLevel` enum contained variants that only made sense for some top-level types.
- The +suffix (`application/text+xml`) was conflated with the sub-level type.
- Exposed representation, so no optimizations were possible.
- A `SubLevel::Other(String)` is a backwards-compatibility hazard for adding new variants that used to parse as `Other`.
### 0.3: `struct Mime`, `mime::TEXT_PLAIN` constants

Still allowed matching, `(mime::TEXT, mime::PLAIN)`.

Cons:

- Couldn't create constant `Mime`s
- Conflates types and ranges
- Conflates `Name`s and `Value`s

### 0.4 (never released): `MediaType`, `MediaRange`, and `mime!` macro.

Separated `Mime` into type and range. The `mime!` macro was meant to allow easier constant creation. It could also allow nicer syntax, such as `mime!("text" / "plain")`, without any extra imports.

Cons:
- Macro required exposing an "\_\_private_dont_use" field that the macro could set. `const fn` has advanced that we probably could live without a macro.

**Comment by djc** [comment]
Have you reviewed other crates to check whether you (and other users) might perhaps be better offer migrating to an existing other option?

**Comment by JonathanWoollett-Light** [comment]
To be frank, do many care about matching and comparisons? My understanding is that the vast majority simply use it as a crate of constants to use instead of strings.

I think that honestly the only changes that matter are maintain an update to date list.

If we want to go further we could simply parse https://www.iana.org/assignments/media-types/media-types.xhtml

**Comment by caneroj1** [comment]
@seanmonstar can we open a call for maintainers? Not to belabor the point, but this crate has a lot of downloads and is an important part of the ecosystem. I think I agree with https://github.com/hyperium/mime/issues/153#issuecomment-2401002882 here -- it does feel a _little_ unreasonable to leave this to rot. I'd be interested in resurrecting the 0.3x branch (since that's what's on crates.io) and go from there. That way, we can get updates to the currently published version of this library, as it seems like there's a fair bit of interest from folks to contribute new features, and then evolution discussions can happen next (or not at all, if there's no appetite to change this that much)?

**Comment by RemiBardon** [comment]
I second opening a call for maintainer. As said the library has a lot of downloads and it seems necessary to have someone able to publish basic updates.

I'm not taking a position regarding a potential rewrite, because frankly I read about it quite a long time ago and it's not fresh in my mind, but security fixes and minor improvements should be released every now and then IMO.

As a side note, I would be wiling to take some time every now and then to help reviving this repo, if needed. I'm currently spending energy on https://github.com/valeriansaliou/sonic but I could easily free up some time for this.

**Comment by kailan** [comment]
We have a few engineers at @fastly that are keen on maintaining the 0.3.x branch as it is, as our customers depend on it. We'd like to contribute here rather than fork and further split the ecosystem. What are the next steps here in order to get the backlog of PRs adding mime types reviewed and merged?

**Comment by JonathanWoollett-Light** [comment]
> We have a few engineers at [@fastly](https://github.com/fastly) that are keen on maintaining the 0.3.x branch

There comes a certain risk with this approach, that if these engineers leave [@fastly](https://github.com/fastly) their motivation to maintain the crate may change (I saw this happen in realtime quite a few times at AWS). While it can be helpful to have maintainers from companies that use the crate, it is probably best long term to have primary maintainers whose motivation is primarily unrelated to their current role. But of course I acknowledge if no one else is going to maintain this crate, being picky here becomes unreasonable.
